name: Build and Deploy Docker Image on ECS

on:
  workflow_dispatch:
  #push:
   # branches:
   #   - master
   #   - main  # You can change this to any branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to AWS ECR
      env:
        AWS_REGION: ap-south-1
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region $AWS_REGION
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 556864637241.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build the Docker image
      env:
        ECR_URL: 556864637241.dkr.ecr.ap-south-1.amazonaws.com
      run: |
        IMAGE_TAG=$(date +%m-%d_%H-%M)
        REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
        IMAGE_NAME="${REPO_NAME}:${IMAGE_TAG}"
        docker build -t "${IMAGE_NAME}" .
        docker tag "${IMAGE_NAME}" ${ECR_URL}/${IMAGE_NAME}
        docker push ${ECR_URL}/${IMAGE_NAME}
        # Capture the Current image URI (tagged as latest)
        CURRENT_IMAGE_URI=${ECR_URL}/${IMAGE_NAME}
        echo "current_image_uri=$CURRENT_IMAGE_URI" >> $GITHUB_ENV
        echo "current_image_tag=$IMAGE_TAG" >> $GITHUB_ENV
        echo "current_image_name=$IMAGE_NAME" >> $GITHUB_ENV
        
    - name: Set up AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli jq

    - name: Capture Previous Task Definition
      id: capture_previous_td
      env:
        AWS_REGION: ap-south-1
        TEST_CLUSTER_NAME: test-cluster
        TEST_SERVICE_NAME: test-service
      run: |
        PREVIOUS_TASK_DEF_ARN=$(aws ecs describe-services --cluster $TEST_CLUSTER_NAME --services $TEST_SERVICE_NAME --query 'services[0].taskDefinition' --output text)
        echo "previous_task_def_arn=$PREVIOUS_TASK_DEF_ARN" >> $GITHUB_ENV

    - name: Deploy to ECS Test Environment.
      env:
        AWS_REGION: ap-south-1
        TEST_CLUSTER_NAME: test-cluster
        TEST_SERVICE_NAME: test-service
        TASK_FAMILY: saad-td
        CONTAINER_NAME: wp
        IMAGE_URL: ${{ env.current_image_uri }}
      run: |
        # Get the latest revision of the task definition
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY)        
        # Update the task definition with the new image and remove unnecessary fields
        NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE_URL "$IMAGE_URL" --arg CONTAINER_NAME "$CONTAINER_NAME" --arg FAMILY "$TASK_FAMILY" '
          .taskDefinition |
          .containerDefinitions[0].image = $IMAGE_URL |
          .family = $FAMILY |
          del(.status, .taskDefinitionArn, .revision, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .taskDefinitionArn)')
        echo "$NEW_TASK_DEF" > new-task-def.json

        # Register the new task definition
        NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
          
        # Set the output for the task definition ARN
        echo "new_task_def_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

        # Update the ECS service to use the new task definition revision
        aws ecs update-service \
          --cluster $TEST_CLUSTER_NAME \
          --service $TEST_SERVICE_NAME \
          --task-definition $NEW_TASK_DEF_ARN \
          --force-new-deployment

        # Wait for the new task to reach the RUNNING state
        NEW_TASK_ARN=$(aws ecs list-tasks --cluster $TEST_CLUSTER_NAME --service-name $TEST_SERVICE_NAME --desired-status RUNNING --query 'taskArns[0]' --output text)
        aws ecs wait tasks-running --cluster $TEST_CLUSTER_NAME --tasks $NEW_TASK_ARN

        # Forcefully delete old tasks
        OLD_TASKS=$(aws ecs list-tasks --cluster $TEST_CLUSTER_NAME --service-name $TEST_SERVICE_NAME --desired-status RUNNING --query 'taskArns[?taskArn!=`'"$NEW_TASK_ARN"'`]' --output text)
        for task in $OLD_TASKS; do
          aws ecs stop-task --cluster $TEST_CLUSTER_NAME --task $task
        done

    - name: Run Integration Tests
      run: |
        # Add your integration test commands here
        echo "Running integration tests..."
        curl -f http://your-test-endpoint/health || exit 1
        # Simulate test pass/failure
        exit 0 # Change this to exit 1 to simulate a failure

    - name: Rollback Test Environment
      if: failure()
      env:
        AWS_REGION: ap-south-1
        TEST_CLUSTER_NAME: test-cluster
        TEST_SERVICE_NAME: test-service
        PREVIOUS_TASK_DEF_ARN: ${{ env.previous_task_def_arn }}
        NEW_TASK_DEF_ARN: ${{ env.new_task_def_arn }}
        IMAGE_TAG: ${{ env.current_image_tag }}
        IMAGE_NAME: ${{ env.current_image_name }}
      run: |
        # Rollback to previous task definition
        aws ecs update-service --cluster $TEST_CLUSTER_NAME --service $TEST_SERVICE_NAME --task-definition $PREVIOUS_TASK_DEF_ARN --force-new-deployment

        # Wait for the rollback task to reach the RUNNING state
        ROLLBACK_TASK_ARN=$(aws ecs list-tasks --cluster $TEST_CLUSTER_NAME --service-name $TEST_SERVICE_NAME --desired-status RUNNING --query 'taskArns[0]' --output text)
        aws ecs wait tasks-running --cluster $TEST_CLUSTER_NAME --tasks $ROLLBACK_TASK_ARN

        # Forcefully delete new tasks created during the failed deployment
        NEW_TASKS=$(aws ecs list-tasks --cluster $TEST_CLUSTER_NAME --service-name $TEST_SERVICE_NAME --desired-status RUNNING --query 'taskArns[?taskArn!=`'"$ROLLBACK_TASK_ARN"'`]' --output text)
        for task in $NEW_TASKS; do
          aws ecs stop-task --cluster $TEST_CLUSTER_NAME --task $task
        done

        # Deregister the new (failed) task definition
        aws ecs deregister-task-definition --task-definition $NEW_TASK_DEF_ARN
        # Delete the newly created image
        aws ecr batch-delete-image --repository-name $IMAGE_NAME --image-ids imageTag=$IMAGE_TAG
      
    - name: Deploy to Production
      if: success()
      env:
        AWS_REGION: ap-south-1
        CLUSTER_NAME: saad-cluster
        SERVICE_NAME: saad-service
        NEW_TASK_DEF_ARN: ${{ env.new_task_def_arn }}
      run: |
        # Deploy to production if tests pass
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN --force-new-deployment
