name: Build Docker Image

on:
  workflow_dispatch:
  #push:
   # branches:
   #   - master
   #   - main  # You can change this to any branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to AWS ECR
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Build and push image to ECR
      run: |
        #TIMESTAMP=$(date +%m-%d_%H-%M)
        #IMAGE_NAME="${{ github.repository }}:latest"
        docker build -t my-node-app .
        docker tag my-node-app:latest $ECR_REGISTRY_URL/my-node-app:latest
        docker push $ECR_REGISTRY_URL/my-node-app:latest
      env:
        ECR_REGISTRY_URL: ${{ steps.login-ecr.outputs.registry-url }}
