name: Build Docker Image

on:
  workflow_dispatch:
  #push:
   # branches:
   #   - master
   #   - main  # You can change this to any branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to AWS ECR
      env:
        AWS_REGION: ap-south-1
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region $AWS_REGION
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 556864637241.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build the Docker image
      run: |
        docker build -t my-node-app .

    - name: Tag the Docker image
      run: |
        docker tag my-node-app:latest 556864637241.dkr.ecr.ap-south-1.amazonaws.com/saad-ecr:latest

    - name: Push the Docker image to ECR
      run: |
        docker push 556864637241.dkr.ecr.ap-south-1.amazonaws.com/saad-ecr:latest
